version: '3'

services:
  webserver:
    image: nginx:latest
    container_name: webserverjogjatravel
    volumes:
      - FPVolume:/var/www/html
      - ./Docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7000:80
    depends_on:
      - app
      - dbjogjatravel
    networks:
      - FPNetwork
    restart: on-failure
  app:
    image: jogjatravel:latest
    build: .
    container_name: jogjatravelapp
    volumes:
      - FPVolume:/var/www/html
    networks:
      - FPNetwork
    depends_on:
      - dbjogjatravel
    restart: on-failure
  dbjogjatravel:
    image: mysql:8.0-debian
    container_name: dbjogjatravel
    environment:
      - MYSQL_ROOT_PASSWORD=1235813
      - MYSQL_DATABASE=fp-pweb
    volumes:
      - FPDatabaseVolume:/var/lib/mysql
      - ./Docker/query.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - FPNetwork
    restart: on-failure

networks:
  FPNetwork: {}

volumes:
  FPVolume: {}
  FPDatabaseVolume: {}